server:
  port: 80

spring:
  application:
    name: order80
  main:
    allow-bean-definition-overriding: true # 允许存在多个Feign调用相同的service接口

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://8.129.110.202:7001/eureka

info:
  version: 2.1
